- op: replace
  path: /spec/replicas
  value: 1
- op: add
  path: /spec/retention
  value: 7d
- op: add
  path: /spec/externalUrl
  value: https://prometheus.k8s.bosh.tokyo
- op: add
  path: /spec/additionalScrapeConfigs
  value:
    key: prometheus-additional.yml
    name: additional-scrape-configs
- op: add
  path: /spec/storage
  value:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
        storageClassName: standard
