- op: add
  path: /metadata/annotations
  value:
    spring.cloud.gateway/routes: |
      predicates:
      - Host=prometheus.k8s.bosh.tokyo
      filters:
      - name: Hystrix
        args:
          name: monitoring/prometheus-k8s
          fallbackUri: forward:/error/503
      - name: Retry
        args:
          retries: 3
          statuses: BAD_GATEWAY