apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgojIFRoZSBkaXJlY3RvcnkgZnJvbSB3aGljaCBub3RpZmljYXRpb24gdGVtcGxhdGVzIGFyZSByZWFkLgp0ZW1wbGF0ZXM6CiMgVGhlIHJvb3Qgbm9kZSBvZiB0aGUgcm91dGluZyB0cmVlCnJvdXRlOgogIHJlY2VpdmVyOiBkZWZhdWx0CiAgZ3JvdXBfd2FpdDogMzBzCiAgZ3JvdXBfaW50ZXJ2YWw6IDVtCiAgcmVwZWF0X2ludGVydmFsOiA0aAogIGdyb3VwX2J5OgogIC0gYWxlcnRuYW1lCiAgIyBDaGlsZCByb3V0ZXMKICByb3V0ZXM6IFtdCiMgQSBsaXN0IG9mIG5vdGlmaWNhdGlvbiByZWNlaXZlcnMKcmVjZWl2ZXJzOgotIG5hbWU6IGRlZmF1bHQKICBzbGFja19jb25maWdzOgogIC0gYXBpX3VybDogaHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDFTVTE3NUg4L0I3OTI5QUtOSC9CamNhR1lVMklyY3FMRHhIbkxiaEd1THcKICAgIGNoYW5uZWw6IGFsZXJ0CiAgICBzZW5kX3Jlc29sdmVkOiB0cnVlCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: monitoring
